/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and readiness check */
        get: operations["get_health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create account (FR-010) */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue access + refresh token (FR-012) */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate refresh token, issue new access token (SEC-023) */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke current refresh token (FR-013) */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Browse/search/filter listings (FR-001..004) */
        get: operations["browse_listings_api_v1_listings_get"];
        put?: never;
        /** Create listing (FR-020, UC-2) */
        post: operations["create_listing_api_v1_listings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/listings/{listing_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listing detail (FR-005/FR-006a/API-012) */
        get: operations["get_listing_api_v1_listings__listing_id__get"];
        put?: never;
        post?: never;
        /** Soft-delete listing — owner-only, idempotent (FR-022/024/027/029, UC-5) */
        delete: operations["delete_listing_api_v1_listings__listing_id__delete"];
        options?: never;
        head?: never;
        /** Edit listing — owner + available-only (FR-021/024/028, UC-3) */
        patch: operations["update_listing_api_v1_listings__listing_id__patch"];
        trace?: never;
    };
    "/api/v1/listings/{listing_id}/sold": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark sold — owner + available-only (FR-023/024, UC-4) */
        post: operations["mark_listing_sold_api_v1_listings__listing_id__sold_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/listings/{listing_id}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload 1+ images, atomically (API-030/031/032) */
        post: operations["upload_listing_images_api_v1_listings__listing_id__images_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Listings — every status (FR-025) */
        get: operations["get_my_listings_api_v1_users_me_listings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/listings/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Listings' counts by status (FR-032) */
        get: operations["get_my_listings_summary_api_v1_users_me_listings_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Own profile (FR-030) */
        get: operations["get_own_profile_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit display name (FR-030/FR-033) */
        patch: operations["update_own_profile_api_v1_users_me_patch"];
        trace?: never;
    };
    "/api/v1/users/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change password — self-initiated or forced (FR-031/FR-015) */
        post: operations["change_own_password_api_v1_users_me_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all users (FR-040) */
        get: operations["list_users_api_v1_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Suspend a user (FR-041, UC-6) */
        post: operations["suspend_user_api_v1_admin_users__user_id__suspend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/reinstate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reinstate a suspended user (FR-041, UC-6) */
        post: operations["reinstate_user_api_v1_admin_users__user_id__reinstate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin-assisted password reset (FR-045, UC-7) */
        post: operations["reset_password_api_v1_admin_users__user_id__reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List listings, any status (FR-043) */
        get: operations["list_listings_api_v1_admin_listings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/listings/{listing_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a listing, reason required (FR-042, UC-5, FR-029) */
        delete: operations["remove_listing_api_v1_admin_listings__listing_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccessTokenResponse
         * @description Returned by both login and refresh — the refresh token itself never
         *     appears in a response body (SEC-022: it only ever travels as an
         *     HttpOnly cookie).
         */
        AccessTokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /**
         * AdminPasswordResetResponse
         * @description FR-045: "return the temporary password once, in the API response to
         *     the admin." This is the only place this value is ever transmitted —
         *     never persisted in plaintext, never logged, never emailed (NG-9/FR-045
         *     are explicit that the system must not email it).
         */
        AdminPasswordResetResponse: {
            /** Temporary Password */
            temporary_password: string;
        };
        /**
         * AdminUserPage
         * @description API-003: pagination metadata shaped as total/page/page_size — same
         *     convention `ListingPage` already established in Milestone 2.
         */
        AdminUserPage: {
            /** Items */
            items: components["schemas"]["AdminUserPublic"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /**
         * AdminUserPublic
         * @description FR-040: "basic metadata (email, display name, created date,
         *     status)". `status` is `is_active` directly (`True`/`False`) rather than
         *     a string enum — there are exactly two states for a `User` (§10.1 has no
         *     third), so a bool is the right-sized shape, the same reasoning
         *     `ListingStatusSummary` (Milestone 3) already used for a small, fixed
         *     set of values. Distinct from `app.modules.users.schemas.UserPublic`:
         *     that schema is what a user sees of *themselves* and deliberately omits
         *     `is_active`/role, since a suspended user doesn't need (and per FR-006
         *     -adjacent reasoning, shouldn't necessarily be told mechanically) their
         *     own account-status field rendered back at them by that endpoint; this
         *     is what an *admin* sees of *any* account, which is a different
         *     audience with different fields.
         */
        AdminUserPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Is Active */
            is_active: boolean;
        };
        /** Body_upload_listing_images_api_v1_listings__listing_id__images_post */
        Body_upload_listing_images_api_v1_listings__listing_id__images_post: {
            /** Images */
            images: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthChecks */
        HealthChecks: {
            /** Database */
            database: string;
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            checks: components["schemas"]["HealthChecks"];
        };
        /**
         * ListingCategoryEnum
         * @description Fixed category list (§10.3) — adding a category is a migration, not a feature.
         * @enum {string}
         */
        ListingCategoryEnum: "fiction" | "non_fiction" | "academic_textbook" | "children" | "comics_graphic_novels" | "other";
        /**
         * ListingConditionEnum
         * @enum {string}
         */
        ListingConditionEnum: "new" | "like_new" | "good" | "fair" | "poor";
        /** ListingCreate */
        ListingCreate: {
            /** Title */
            title: string;
            /** Author */
            author: string;
            /** Description */
            description: string;
            category: components["schemas"]["ListingCategoryEnum"];
            condition: components["schemas"]["ListingConditionEnum"];
            /** Price */
            price: number | string;
        };
        /** ListingImagePublic */
        ListingImagePublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Url */
            url: string;
            /** Position */
            position: number;
        };
        /**
         * ListingPage
         * @description API-003: pagination metadata shaped as total/page/page_size — never
         *     a raw offset — so the contract could be swapped to cursor-based later
         *     without a breaking change.
         */
        ListingPage: {
            /** Items */
            items: components["schemas"]["ListingPublic"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /**
         * ListingPublic
         * @description FR-005's detail shape, also reused for browse/My-Listings list items
         *     (§13.1 has no distinct "card" shape, and this scale doesn't justify
         *     maintaining two nearly-identical schemas — see IMPLEMENTATION_SUMMARY.md).
         *
         *     FR-006: no seller contact info (email/phone) — only `seller_display_name`.
         */
        ListingPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /** Seller Display Name */
            seller_display_name: string;
            /** Title */
            title: string;
            /** Author */
            author: string;
            /** Description */
            description: string;
            category: components["schemas"]["ListingCategoryEnum"];
            condition: components["schemas"]["ListingConditionEnum"];
            /** Price */
            price: string;
            status: components["schemas"]["ListingStatusEnum"];
            /** Sold At */
            sold_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Images */
            images: components["schemas"]["ListingImagePublic"][];
        };
        /**
         * ListingStatusEnum
         * @enum {string}
         */
        ListingStatusEnum: "available" | "sold" | "deleted";
        /**
         * ListingStatusSummary
         * @description FR-032: "a summary of their own listings' counts by status." Explicit
         *     fields for the three fixed status values — not a dynamically-keyed
         *     `dict[str, int]` — for the same reason `category`/`condition` are fixed
         *     enums rather than free-text (§10.3/10.4): exactly three values that
         *     change on the order of "never", so a typed, self-documenting shape
         *     (each key visible in the OpenAPI schema, per API-021) is the
         *     right-sized choice over a schema-less mapping a client would have to
         *     infer the keys of.
         */
        ListingStatusSummary: {
            /** Available */
            available: number;
            /** Sold */
            sold: number;
            /** Deleted */
            deleted: number;
        };
        /**
         * ListingUpdate
         * @description FR-021: full field set editable while `available` (FR-028) — every
         *     field optional so a PATCH can change just one. `model_dump(exclude_unset=True)`
         *     is what distinguishes "field omitted" from "field explicitly resent
         *     unchanged" at the service layer, not any default value here.
         */
        ListingUpdate: {
            /** Title */
            title?: string | null;
            /** Author */
            author?: string | null;
            /** Description */
            description?: string | null;
            category?: components["schemas"]["ListingCategoryEnum"] | null;
            condition?: components["schemas"]["ListingConditionEnum"] | null;
            /** Price */
            price?: number | string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * PasswordChangeRequest
         * @description FR-031. `current_password` carries the same field name regardless of
         *     whether the caller is doing a self-initiated change (a password they
         *     remember) or completing the forced-change flow (FR-015) with the
         *     one-time temporary password from FR-045 — from the API's perspective
         *     both are just "prove you know the password on the account right now",
         *     verified identically by `UserService.change_password`. No length
         *     constraint on `current_password` itself: it's being verified against a
         *     stored hash, not freshly validated against SEC-011's policy.
         */
        PasswordChangeRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Display Name */
            display_name: string;
        };
        /**
         * RoleEnum
         * @description §6 — exactly two roles; ownership checks, not roles, gate seller/buyer actions.
         * @enum {string}
         */
        RoleEnum: "user" | "admin";
        /**
         * SuspendUserRequest
         * @description §10.1: `reason_code` is required for `suspend_user`.
         *
         *     `remove_listing` also requires a `reason_code` (§10.1), but
         *     `DELETE /admin/listings/{id}` takes it as a query parameter instead of
         *     a body — deliberately not a second, near-identical schema shared with
         *     this one. That split is not stylistic: `httpx`'s (and therefore
         *     `TestClient`'s) `Client.delete()` has no `json`/`content` parameter at
         *     all in this project's pinned version, only `DELETE /listings/{id}`'s
         *     kind of body-less delete is actually exercisable through it without
         *     dropping to the low-level `.request("DELETE", ...)` call — and more
         *     fundamentally, a request body on `DELETE` has no defined semantics in
         *     HTTP itself and is inconsistently supported by proxies/clients in the
         *     wild, which is exactly the kind of "technically legal, practically
         *     fragile" corner this project avoids elsewhere. `POST /suspend` has
         *     no such issue — a body on `POST` is completely unremarkable — so it
         *     keeps the schema/`API-020` treatment `reinstate_user`'s bodyless
         *     `POST` and every other mutating endpoint in this codebase already gets.
         *     `reinstate_user`/`reset_password` don't use this at all: §10.1 states
         *     `reason_code` is "not applicable to reset_password", and nothing in
         *     FR-041/UC-6 asks for one on reinstate either — only the
         *     punitive/moderation actions require a stated reason.
         */
        SuspendUserRequest: {
            /** Reason Code */
            reason_code: string;
        };
        /**
         * UserPublic
         * @description Bugfix, discovered during Milestone 5 (frontend build-out): `role`
         *     was missing from this schema entirely. §6/FR-040 make `role` a
         *     genuinely public-to-its-owner fact (a user already knows whether
         *     they're an admin — this is not the kind of "other users' data" leak
         *     `UserPublic`'s exclusions above guard against), and nothing else in
         *     the API surface can substitute for it: the JWT access token payload
         *     carries only `sub`/`type`/`iat`/`exp` (SEC-020) with no role claim by
         *     design (a stateless claim would need to be treated as authoritative,
         *     reintroducing exactly the "trust a client-supplied/cached field for
         *     authorization" problem SEC-031 forbids), and admin authorization is
         *     correctly re-checked server-side on every request regardless
         *     (`require_admin`, Milestone 4) — so exposing `role` here changes
         *     nothing about how *authorization* works, it only lets the frontend
         *     decide whether to *render* admin navigation/pages at all. Without it,
         *     Milestone 5's admin UI has no non-hacky way to know whether the
         *     logged-in user should see it.
         */
        UserPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            role: components["schemas"]["RoleEnum"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * UserUpdate
         * @description FR-030's only editable field. Not modeled as an optional/partial-PATCH
         *     field the way `ListingUpdate` models several independently-optional
         *     fields (Milestone 2) — `display_name` is the *only* thing FR-030 permits
         *     editing (FR-033 forbids email changes outright, so there is no second
         *     field for `exclude_unset` to meaningfully distinguish), so requiring it
         *     directly is simpler than an all-optional schema that could legitimately
         *     be submitted empty.
         */
        UserUpdate: {
            /** Display Name */
            display_name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    browse_listings_api_v1_listings_get: {
        parameters: {
            query?: {
                search?: string | null;
                category?: components["schemas"]["ListingCategoryEnum"] | null;
                condition?: components["schemas"]["ListingConditionEnum"] | null;
                min_price?: number | string | null;
                max_price?: number | string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_listing_api_v1_listings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_listing_api_v1_listings__listing_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listing_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_listing_api_v1_listings__listing_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listing_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_listing_api_v1_listings__listing_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listing_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListingUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_listing_sold_api_v1_listings__listing_id__sold_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listing_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_listing_images_api_v1_listings__listing_id__images_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listing_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_listing_images_api_v1_listings__listing_id__images_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingImagePublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_listings_api_v1_users_me_listings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingPublic"][];
                };
            };
        };
    };
    get_my_listings_summary_api_v1_users_me_listings_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingStatusSummary"];
                };
            };
        };
    };
    get_own_profile_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
        };
    };
    update_own_profile_api_v1_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_own_password_api_v1_users_me_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_admin_users_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suspend_user_api_v1_admin_users__user_id__suspend_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuspendUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reinstate_user_api_v1_admin_users__user_id__reinstate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_api_v1_admin_users__user_id__reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPasswordResetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_listings_api_v1_admin_listings_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ListingStatusEnum"] | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_listing_api_v1_admin_listings__listing_id__delete: {
        parameters: {
            query: {
                reason_code: string;
            };
            header?: never;
            path: {
                listing_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
