"""Initial schema: citext extension, users, listings, listing_images,
refresh_tokens, admin_actions.

Hand-written rather than autogenerated, so every choice in §10/§11 (enum
names, cascade behavior, generated column, index set) is explicit and
reviewable in one place, matching how the domain model and database
requirements sections of the SRS are written.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-07-30

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import CITEXT, TSVECTOR, UUID

# revision identifiers, used by Alembic.
revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # --- DB-004: citext extension, required before users.email is created ---
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")

    # --- users (§10.1) --------------------------------------------------------
    op.create_table(
        "users",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("email", CITEXT(), nullable=False, unique=True),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("user", "admin", name="role_enum", native_enum=True),
            nullable=False,
            server_default="user",
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("must_change_password", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    # unique=True above already creates a unique index backing DB-043; the
    # explicit index below is for is_active (DB-044).
    op.create_index("ix_users_is_active", "users", ["is_active"])

    # --- listings (§10.1) -------------------------------------------------------
    op.create_table(
        "listings",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "owner_id",
            UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("author", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "fiction",
                "non_fiction",
                "academic_textbook",
                "children",
                "comics_graphic_novels",
                "other",
                name="listing_category_enum",
                native_enum=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "condition",
            sa.Enum(
                "new",
                "like_new",
                "good",
                "fair",
                "poor",
                name="listing_condition_enum",
                native_enum=True,
            ),
            nullable=False,
        ),
        sa.Column("price", sa.Numeric(10, 2), nullable=False),
        sa.Column(
            "status",
            sa.Enum("available", "sold", "deleted", name="listing_status_enum", native_enum=True),
            nullable=False,
            server_default="available",
        ),
        sa.Column("sold_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "search_vector",
            TSVECTOR(),
            sa.Computed(
                "to_tsvector('english', coalesce(title, '') || ' ' || coalesce(author, ''))",
                persisted=True,
            ),
            nullable=True,
        ),
        sa.CheckConstraint("price > 0", name="ck_listings_price_positive"),
    )
    op.create_index("ix_listings_owner_id", "listings", ["owner_id"])
    op.create_index("ix_listings_status", "listings", ["status"])  # DB-040
    op.create_index(
        "ix_listings_status_category_condition",
        "listings",
        ["status", "category", "condition"],
    )  # DB-041
    op.execute(
        "CREATE INDEX ix_listings_search_vector ON listings USING GIN (search_vector)"
    )  # DB-042

    # --- listing_images (§10.1) -------------------------------------------------
    op.create_table(
        "listing_images",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "listing_id",
            UUID(as_uuid=True),
            sa.ForeignKey("listings.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("object_key", sa.String(), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    op.create_index("ix_listing_images_listing_id", "listing_images", ["listing_id"])

    # --- refresh_tokens (§10.1, added in SRS 2.1.0) -----------------------------
    op.create_table(
        "refresh_tokens",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("token_hash", sa.String(), nullable=False, unique=True),
        sa.Column("family_id", UUID(as_uuid=True), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    op.create_index("ix_refresh_tokens_user_id", "refresh_tokens", ["user_id"])
    op.create_index("ix_refresh_tokens_family_id", "refresh_tokens", ["family_id"])

    # --- admin_actions (§10.1) ---------------------------------------------------
    op.create_table(
        "admin_actions",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "admin_id",
            UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "action_type",
            sa.Enum(
                "remove_listing",
                "suspend_user",
                "reinstate_user",
                "reset_password",
                name="admin_action_type_enum",
                native_enum=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "target_type",
            sa.Enum("listing", "user", name="admin_target_type_enum", native_enum=True),
            nullable=False,
        ),
        sa.Column("target_id", UUID(as_uuid=True), nullable=False),
        sa.Column("reason_code", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    op.create_index("ix_admin_actions_admin_id", "admin_actions", ["admin_id"])


def downgrade() -> None:
    # Reverse FK-dependency order: children before parents.
    op.drop_index("ix_admin_actions_admin_id", table_name="admin_actions")
    op.drop_table("admin_actions")

    op.drop_index("ix_refresh_tokens_family_id", table_name="refresh_tokens")
    op.drop_index("ix_refresh_tokens_user_id", table_name="refresh_tokens")
    op.drop_table("refresh_tokens")

    op.drop_index("ix_listing_images_listing_id", table_name="listing_images")
    op.drop_table("listing_images")

    op.execute("DROP INDEX IF EXISTS ix_listings_search_vector")
    op.drop_index("ix_listings_status_category_condition", table_name="listings")
    op.drop_index("ix_listings_status", table_name="listings")
    op.drop_index("ix_listings_owner_id", table_name="listings")
    op.drop_table("listings")

    op.drop_index("ix_users_is_active", table_name="users")
    op.drop_table("users")

    # Enum types are not dropped automatically by drop_table — drop them
    # explicitly now that no column references them.
    for enum_name in (
        "admin_target_type_enum",
        "admin_action_type_enum",
        "listing_status_enum",
        "listing_condition_enum",
        "listing_category_enum",
        "role_enum",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")

    # The citext extension is intentionally left in place on downgrade: it is
    # a database-wide capability, dropping it is not required to reverse this
    # migration's data model, and forcibly removing it risks erroring if
    # anything else in the database happens to depend on it. This is a
    # documented no-op per DB-002's allowance for that pattern.
