import { execFileSync } from "node:child_process";
import path from "node:path";

/**
 * The one "safe test-only mechanism" this suite uses for admin access:
 * there is no self-service admin registration or promotion endpoint (by
 * design — see SRS §6/§15.4), so admin E2E coverage needs *some* way to
 * get an admin account, exactly like Milestone 4/5's own manual
 * verification did ("admin promotes a user via direct SQL", per
 * IMPLEMENTATION_SUMMARY.md). This runs that identical query, scoped to
 * this suite's own throwaway Docker Compose database — never a
 * production database (that's out of reach entirely: this shells out to
 * `docker compose exec`, which only ever targets the `db` service defined
 * in the repo's own docker-compose.yml).
 *
 * `execFileSync` (argv array, no shell) rather than a template-stringed
 * shell command — even though every value passed in today is generated by
 * this suite's own `test-data.ts`, not attacker input, there is no reason
 * to open a shell-injection shaped hole for a helper whose whole job is
 * running SQL.
 */

const REPO_ROOT = path.resolve(__dirname, "..", "..");

// Test data only ever contains this shape (see `uniqueEmail`/UUIDs
// returned by the API) — rejecting anything else is a cheap, explicit
// backstop against ever interpolating something unexpected into SQL.
const SAFE_LITERAL = /^[a-zA-Z0-9@._-]+$/;

function assertSafeLiteral(value: string): void {
  if (!SAFE_LITERAL.test(value)) {
    throw new Error(`Refusing to interpolate unsafe value into SQL: ${JSON.stringify(value)}`);
  }
}

function runSql(sql: string): string {
  return execFileSync(
    "docker",
    ["compose", "exec", "-T", "db", "psql", "-U", "punah", "-d", "punah_pustak", "-tA", "-c", sql],
    { cwd: REPO_ROOT, encoding: "utf-8" },
  ).trim();
}

/** Direct-SQL admin promotion — the local/CI equivalent of what a real
 * operator would do once, by hand, against their own deployment. */
export function promoteUserToAdmin(email: string): void {
  assertSafeLiteral(email);
  runSql(`UPDATE users SET role = 'admin' WHERE email = '${email}';`);
}

/** SRS TEST-011 flow 2's "corresponding AdminAction rows exist" assertion
 * — the admin UI has no audit-log viewer (moderation is admin-only by
 * design, see FR-044), so the append-only `admin_actions` table itself is
 * the only place this can be verified. */
export function countAdminActions(actionType: string, targetId: string): number {
  assertSafeLiteral(actionType);
  assertSafeLiteral(targetId);
  const out = runSql(
    `SELECT count(*) FROM admin_actions WHERE action_type = '${actionType}' AND target_id = '${targetId}';`,
  );
  return Number(out);
}

/** Resolves a user's UUID by email — used only to build the `target_id`
 * for `countAdminActions` above when the target is a user (suspend), since
 * the admin UI never surfaces a user's raw id. */
export function getUserIdByEmail(email: string): string {
  assertSafeLiteral(email);
  const out = runSql(`SELECT id FROM users WHERE email = '${email}';`);
  if (!out) {
    throw new Error(`No user found with email ${email}`);
  }
  return out;
}
